### ISSUE TITLE
searching for .org or .net returns .org.com and .net.com

### ISSUE THREAD

**Issue by chivitli** [novutec/DomainParser#1]
It seems that .org and .net are not in the list of tld's, so .com is automatically appended to such domain names

**Comment by adduc** [comment]
Do you have an example domain, or sample code? I haven't been able to replicate this.

**Comment by chivitli** [comment]
Yes, I just tested again with the latest master version

`require_once 'DomainParser/Parser.php';`
`require_once 'WhoisParser/Parser.php';`

`$Parser = new Novutec\WhoisParser\Parser();`
`$result = $Parser->lookup('wikipedia.org');`
`var_dump($result);`

It returns

`object(Novutec\WhoisParser\Result)#2 (18) { ["name":protected]=> string(17) "wikipedia.org.com" ["idnName":protected]=> string(17) "wikipedia.org.com" ["status":protected]=> NULL ["nameserver":protected]=> NULL ["ips":protected]=> NULL ["created":protected]=> NULL ["changed":protected]=> NULL ["expires":protected]=> NULL ["registered":protected]=> bool(false) ["dnssec":protected]=> bool(false) ["whoisserver":protected]=> string(22) "whois.verisign-grs.com" ["contacts":protected]=> object(stdClass)#3 (0) { } ["registrar":protected]=> NULL ["rawdata":protected]=> array(9) { [0]=> string(0) "" [1]=> string(24) "Whois Server Version 2.0" [2]=> string(0) "" [3]=> string(63) "Domain names in the .com and .net domains can now be registered" [4]=> string(71) "with many different competing registrars. Go to http://www.internic.net" [5]=> string(25) "for detailed information." [6]=> string(0) "" [7]=> string(40) "No match for domain "WIKIPEDIA.ORG.COM"." [8]=> string(65) ">>> Last update of whois database: Sun, 02 Jun 2013 13:21:35 UTC " } ["network":protected]=> NULL ["exception":protected]=> NULL ["parsedContacts":protected]=> bool(false) ["template":protected]=> string(8) "verisign" }`

**Comment by adduc** [comment]
Running your code using the latest versions of DomainParser and WhoisParser, I see accurate domain resolution.

Are you running old versions of DomainParser/WhoisParser?

My code: 

```
<?php

include('vendor/autoload.php');

$Parser = new Novutec\WhoisParser\Parser();
$result = $Parser->lookup('wikipedia.org');
var_dump($result);
```

What it returned for me (truncated for readability):

```
class Novutec\WhoisParser\Result#3 (18) {
    protected $name =>
    string(13) "wikipedia.org"
    protected $idnName =>
    string(13) "wikipedia.org"
    .
    .
    .
```

**Comment by chivitli** [comment]
I used the latest version from Github. Are you sure that you haven't tested against the cached version of `domainparsertld.txt`?

I traced the problem to this line, after which `org` seems to dissapear, in `DomainParser\Parser.php:348`

`preg_match_all('/\/\/ ([a-z0-9\-]+) ([a-z\-\(\)\.\/<>" ]+ : [a-z]{2}|: (see )?(http|https):\/\/.+?|No registrations at this time.|This registry is effectively dormant|has 2nd-level tlds, but there\'s no list of them)[\r\n]{0,2}(.+?)(?=(\/\/ (?!municipalities|Norid|Non-Norid|domaines)([a-z0-9\-]*) (:|[a-z\-\(\)\.\/<>" ]+ : [a-z]{2})|$))/is', $matches[1], $matches);`

If I remove it and change the next line to `foreach ($matches as $num => $block) {`, I get the correct result

**Comment by seitsu** [comment]
I have tested it with the latest Github version and the latest development version of mine and it works for me. Could you provide your domainparsertld.txt? Maybe there is something wrong by downloading and parsing it.

**Comment by chivitli** [comment]
Here is the file: https://gist.github.com/chivitli/5699298

It may be related to PHP version. The same code which runs incorrectly on PHP 5.3.4 on Linux/Windows, runs correctly on PHP 5.3.23 on Linux.

**Comment by jlsanz** [comment]
I also get incorrect lookups when searching for '.net', '.org', etc, with '.com' appended.
CentOS 6.4 x86_64. php-5.3.3-22.el6.x86_64

I think it's because of some php parsing issue or limit on php regexp. From http://www.php.net/manual/en/regexp.reference.subpatterns.php :
"The maximum number of captured substrings is 99, and the maximum number of all subpatterns, both capturing and non-capturing, is 200."

DomainParser/Parser.php correctly downloads file from http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1, but it stops parsing on '.jp', which includes a huge 4th level domain list. So it ends up with a limited array of domains, which doesn't include '.net', '.org', and so on. When a lookup is performed later, the search can't find those tld and defaults to appending '.com'.

If I filter out those jp 4th level domains in function catchTlds of Parser.php, everything works as expected:
$tlds = array();
$content = preg_replace('/[a-z0-9-]+.[a-z0-9-]+.jp[\r\n]{1,2}/', '', $content);
...

**Comment by jlsanz** [comment]
sorry, this form took away some backslashes, I mean
$content = preg_replace('/[a-z0-9\-]+\.[a-z0-9\-]+\.jp[\r\n]{1,2}/', '', $content);

**Comment by koroban** [comment]
Thank you for your comments - should be fixed by the latest release. Could you please check if the error is still present?

**Comment by chivitli** [comment]
Fix confirmed, returned results are now correct.
